### ISSUE TITLE
Взаимоисключающие параграфы в лицензии

### ISSUE THREAD

**Issue by ghost** [kesha4/UplinkOS_rus#2]
Лицензия перевода содержит взаимоисключающие параграфы:

Лицензия перевода

**Этот перевод является свободным программным обеспечением.** Вы можете распространять и/или модифицировать его с сохранением указания автора проекта (Сергей "kesha4" Макаров). **Нельзя использовать данный перевод и его производные для получения денежной выгоды или продавать.** Этот перевод распространяется в надежде, что он будет полезен, но БЕЗ ВСЯКИХ ГАРАНТИЙ, в том числе подразумеваемых гарантий ТОВАРНОГО СОСТОЯНИЯ ПРИ ПРОДАЖЕ и ГОДНОСТИ ДЛЯ ОПРЕДЕЛЁННОГО ПРИМЕНЕНИЯ. Автор не несет никакой ответственности в случае неполадок вызванных данным продуктом, а также в случае возникновения острого психоза на фоне неточности перевода.

Свободное программное обеспечение _можно_ продавать.
Программное обеспечение, которое _нельзя_ продавать, не может быть свободным.

См. https://gnu.org/

**Comment by kesha4** [comment]
Спасибо, исправил.
